import { TopicPreset } from './types';

export const TOPIC_PRESETS: TopicPreset[] = [
  {
    id: 'ai-debate',
    title: 'Debate: ¿La IA reemplazará a los programadores?',
    category: 'Tecnología & Futuro',
    topic: 'Un debate entusiasta y con argumentos técnicos sobre si la inteligencia artificial reemplazará por completo a los desarrolladores de software o si se convertirá en su herramienta más poderosa.',
    speaker1Name: 'Mateo',
    speaker1Role: 'Ingeniero escéptico y defensor del criterio humano',
    speaker1Voice: 'Fenrir',
    speaker2Name: 'Lucía',
    speaker2Role: 'Investigadora de IA entusiasta y visionaria',
    speaker2Voice: 'Kore',
  },
  {
    id: 'job-interview',
    title: 'Entrevista de Trabajo: Puesto de Liderazgo',
    category: 'Profesional & Negocios',
    topic: 'Una entrevista de trabajo dinámica donde el reclutador indaga sobre cómo manejar situaciones de alta presión y la candidata responde con ejemplos concretos y liderazgo empático.',
    speaker1Name: 'Roberto',
    speaker1Role: 'Director de Recursos Humanos exigente pero cordial',
    speaker1Voice: 'Charon',
    speaker2Name: 'Valeria',
    speaker2Role: 'Candidata experimentada, segura y elocuente',
    speaker2Voice: 'Zephyr',
  },
  {
    id: 'coffee-catchup',
    title: 'Café entre Amigos: Planes de Emprendimiento',
    category: 'Casual & Amistad',
    topic: 'Dos amigos de toda la vida se encuentran en una cafetería para ponerse al día y uno le cuenta al otro con gran emoción su nueva idea para abrir una pastelería artesanal.',
    speaker1Name: 'Santiago',
    speaker1Role: 'Amigo soñador, enérgico y creativo',
    speaker1Voice: 'Puck',
    speaker2Name: 'Camila',
    speaker2Role: 'Amiga sensata, analítica y con consejos prácticos',
    speaker2Voice: 'Kore',
  },
  {
    id: 'science-podcast',
    title: 'Minipodcast: ¿Qué hay dentro de un Agujero Negro?',
    category: 'Divulgación Científica',
    topic: 'Dos divulgadores científicos explican de forma fascinante, accesible y con analogías cotidianas qué sucedería si te acercaras al horizonte de sucesos de un agujero negro.',
    speaker1Name: 'David',
    speaker1Role: 'Físico curioso y narrador apasionado',
    speaker1Voice: 'Fenrir',
    speaker2Name: 'Sofía',
    speaker2Role: 'Astrofísica didáctica y amena',
    speaker2Voice: 'Zephyr',
  },
  {
    id: 'travel-itinerary',
    title: 'Planificando Vacaciones: ¿Playa o Montaña?',
    category: 'Estilo de Vida & Viajes',
    topic: 'Una pareja discute con humor y cariño a dónde viajar en sus próximas vacaciones, sopesando la tranquilidad del mar versus la aventura y el senderismo en la cordillera.',
    speaker1Name: 'Nicolás',
    speaker1Role: 'Amante de la aventura y el senderismo',
    speaker1Voice: 'Puck',
    speaker2Name: 'Daniela',
    speaker2Role: 'Amante del sol, la lectura y el relax',
    speaker2Voice: 'Kore',
  },
];
